# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Calais
version:      1.01
version_from: lib/Net/Calais.pm
installdirs:  site
requires:
    LWP:                           5.09
    XML::Writer:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
